### ISSUE TITLE
Отсутствие динамического отображения типа двигателя автомобилей.

### ISSUE THREAD

**Issue by swash66** [Rsengo/Lab5_Rsengo#1]
При выборе автомобиля из списка двигатель должен подсвечиваться автоматически в соответствии с выбранным автомобилем. Но этого нет, поэтому пользователь не может узнать тип двигателя существующего автомобиля.
![image](https://cloud.githubusercontent.com/assets/26200527/26287497/0ecea31a-3ea7-11e7-847e-47589d5d46ff.png)

**Comment by Rsengo** [comment]
Ошибка исправлена. В соответствии с выбранным автомобилем на соответствующий RadioButton для св-ва Checked устанавливается значение true.

**Comment by swash66** [comment]
Ошибка была исправлена.
