### ISSUE TITLE
Ошибка выполнения программы при вводе данных неподходящего типа.

### ISSUE THREAD

**Issue by swash66** [Rsengo/Lab5_Rsengo#2]
При создании автомобиля пользователь вводит цену автомобиля. Но если он введет данные , например, типа String, то программа не выполнится и выдаст ошибку. Для исправления ошибки рекомендую обработать тип вводимых данных.
![image](https://cloud.githubusercontent.com/assets/26200527/26287516/6e9a9736-3ea7-11e7-9ea1-6e53882533a4.png)

**Comment by Rsengo** [comment]
Исправил ошибку, обработал исключение для данных, введенных в это поле.

**Comment by swash66** [comment]
Ошибка была исправлена.
